import type { Metadata } from "next";
import { Geist_Mono, Nunito_Sans, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import cn from "@/lib/utils/cn";

const nunitoSans = Nunito_Sans({subsets:['latin'],variable:'--font-nunito-sans'});

const bricolage = Bricolage_Grotesque({subsets:['latin'],variable:'--font-bricolage'});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistMono.variable, "font-sans", nunitoSans.variable, bricolage.variable)}
    >
      <body className="h-full">
        {children}
      </body>
    </html>
  );
}
